#
#  Use this makefile to create feelin.library
#

COMP := @ gcc -noixemul -Wall -mcrt=newlib -O2 -D__USE_BASETYPE__ -DF_USE_PICASSO96 -I/Feelin/Include
LIBS := -lauto

all: Prefs_OS4 Setup_OS4

Prefs_OS4 : Prefs.c

	@ echo ">>"[1m$(@F)[0m
	@ $(COMP) -o $@ $^ $(LIBS)

Setup_OS4 : Setup.c

	@ echo ">>"[1m$(@F)[0m
	@ $(COMP) -o $@ $^ $(LIBS)

